[package]
name = "neva_macros"
version = "0.2.1"
edition = "2024"
rust-version = "1.90.0"
authors = ["Roman Emreis <roman.emreis@outlook.com>"]
license = "MIT"
repository = "https://github.com/RomanEmreis/neva"
description = "Macros for Neva"
documentation = "https://docs.rs/neva"
readme = "README.md"
categories = ["web-programming::http-server", "web-programming::http-client", "network-programming", "asynchronous"]
keywords = ["modelcontextprotocol", "mcp", "sdk", "ai", "framework"]

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
quote = "1.0.42"
syn = { version = "2.0.110", features = ["full"] }
proc-macro2 = "1.0.103"

[features]
default = []
server = []
client = []