[package]
name = "large_resources_server"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
neva = { path = "../../neva", features = ["server-full"] }
tokio = { version = "1.48.0", features = ["full"] }
